---
title: "Job Satisfaction"
author: "Shirley Chen, Jessica Im"
thanks: ""
platform available at: "TBA"
date: March 4, 2024
date-format: "long" 
format: pdf
toc: true
number-sections: true
editor: 
  markdown: 
    wrap: sentence
---

```{r}
#| include: false
### Workspace Setup ###
library(tidyverse)
library(janitor)
library(readr)
library(opendatatoronto)
library(here)
library(ggplot2)
library(knitr)
library(usethis)
library(gitcreds)
library(kableExtra)

#### Import data ####
# Question 1 Dataset
cleaned_GSS_data = read_csv(
  file = here("outputs/data/cleaned_GSS_data.csv"),
  show_col_types = FALSE
)

ordered_responses <- c('very_important', 
                       'important',
                       'neutral',
                       'not_important',
                       'not_important_at_all')
```

```{r}
#| echo: false
#| fig-cap: Q1 - "A job that allows someone to help other people?"

# Helping Others Data
helping_others_data <- cleaned_GSS_data[c('year', 'helping_others')]

helping_others_percentages <- helping_others_data |>
  count(year, helping_others) |>
  group_by(year) |>
  mutate(percentage = n / sum(n) * 100) 

helping_others_percentages$helping_others <- factor(
  helping_others_percentages$helping_others, levels = ordered_responses)

ggplot(helping_others_percentages, aes(
  x = as.factor(year),
  y = percentage, 
  fill = helping_others)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Helping Others Responses by Year",
       x = "Year",
       y = "Percentage",
       fill = "Response") +
  scale_y_continuous(labels = scales::percent_format(scale = 1), 
                     limits = c(0, 100)) + 
  theme_minimal()

```

```{r}
#| echo: false
#| fig-cap: Q2 - "An interesting job?"
#| 
# Interesting Work Data
interesting_work_data <- cleaned_GSS_data[c('year', 'interesting_work')]

interesting_work_percentages <- interesting_work_data |>
  count(year, interesting_work) |>
  group_by(year) |>
  mutate(percentage = n / sum(n) * 100) 

interesting_work_percentages$interesting_work <- factor(
  interesting_work_percentages$interesting_work, levels = ordered_responses)

ggplot(interesting_work_percentages, aes(
  x = as.factor(year),
  y = percentage, 
  fill = interesting_work)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Interesting Work Responses by Year",
       x = "Year",
       y = "Percentage",
       fill = "Response") +
  scale_y_continuous(labels = scales::percent_format(scale = 1), 
                     limits = c(0, 100)) + 
  theme_minimal()
```

```{r}
#| echo: false
#| fig-cap: Q3 - "A job that is useful to society?"
#| 
# Social Usefulness Data
social_usefulness_data <- cleaned_GSS_data[c('year', 'social_usefulness')]

social_usefulness_percentages <- social_usefulness_data |>
  count(year, social_usefulness) |>
  group_by(year) |>
  mutate(percentage = n / sum(n) * 100) 

social_usefulness_percentages$social_usefulness <- factor(
  social_usefulness_percentages$social_usefulness, levels = ordered_responses)

ggplot(social_usefulness_percentages, aes(
  x = as.factor(year),
  y = percentage, 
  fill = social_usefulness)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Social Usefulness Responses by Year",
       x = "Year",
       y = "Percentage",
       fill = "Response") +
  scale_y_continuous(labels = scales::percent_format(scale = 1), 
                     limits = c(0, 100)) + 
  theme_minimal()
```
